name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
      
    - name: Geração do pacote
      run: |
        cd src
        dotnet build -c Release -o out
    
    - name: Push no NuGet
      run: |
        cd src
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.RAVEN_DRIVE_DB_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
